# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='rollNum',
            field=models.IntegerField(),
        ),
    ]
